### ISSUE TITLE
Failed when building NEMO_player

### ISSUE THREAD

**Issue by minhkstn** [kaist-ina/nemo-main#1]
Hi,
I tried building your NEMO_player but it returned failure: 
`Cause: executing external native build for ndkBuild /home/minh/Documents/nemo_public/android_app/NEMO_player/ExoPlayer/extensions/vp9/src/main/jni/Android.mk`

I got the same issue with some other projects like `exo_snpe_battery`, and `snpe_libvpx`. 
Currently, is your source code ready for test?

Thanks!

**Comment by chaos5958** [comment]
Currently, some module are missing due to license issues (e.g., Qualcomm SNPE).
I'll write a guideline as soon as possible.
(Due to personal issues, I cannot not handle right now, sorry.)

**Comment by chaos5958** [comment]
Codec and cache profile are available now.
Player will be available soon.
Sorry for the late updates.
