### ISSUE TITLE
SR model is not trainable

### ISSUE THREAD

**Issue by zhaoyuan-he** [kaist-ina/nemo-main#13]
Hi, 

I hope you are doing well! 

I'm trying to train your SR model in the docker container, but the video quality cannot be improved across all epochs (PSNR (bilinear) - 30.26dB, PSNR (SR) - 4.21dB). The SR PSNR is consistently below 5dB, so I believe the model is not trained. I followed your instructions to prepare, encode videos, and train the model. Could you give me a pointer on how to make the model trainable? 

Thanks a lot!

**Comment by zhaoyuan-he** [comment]
Nvm, I fixed the issue.

**Comment by Wenbin-Tian** [comment]
Hi,
how did you solve this problem?
