### ISSUE TITLE
Can't find codec, cache_profile, and player

### ISSUE THREAD

**Issue by yuqian2019** [kaist-ina/nemo-main#2]
Hi!
I can find codec, cache_profile, and player code in ./nemo folder.
Will you upload it to Github？

Thanks!

**Comment by chaos5958** [comment]
Sure, it will be uploaded soon, sorry for late updates.
I'll close this issue as soon as I push the commits.

**Comment by yuqian2019** [comment]
> Sure, it will be uploaded soon, sorry for late updates.
> I'll close this issue as soon as I push the commits.
Looking forward to ur upload. Ur work is very good!

**Comment by chaos5958** [comment]
Codec and cache profile are updated now. 
Sorry for the late updates.
Player would be also available soon.
