### ISSUE TITLE
Sub-pixel convolution by user-defined operations in SNPE

### ISSUE THREAD

**Issue by yuqian2019** [kaist-ina/nemo-main#4]
I have mentioned tf.nn.depth_to_space not be defined in SNPE's GPU version, and u had tried to define tf.nn.depth_to_space. I have a problem here. Can u share these codes? I will thank you very much!

**Comment by chaos5958** [comment]
I have not used subpixel convolution in practice. Instead I used deconvolution which is supported by SNPE.
