### ISSUE TITLE
Build the SR-integrated codec (arm64-v8) Error, jni/libvpx_android_configs/arm64-v8a/config.mk No such file

### ISSUE THREAD

**Issue by estimate123** [kaist-ina/nemo-main#5]
Hi, I try to build the SR-integrated codec (arm64-v8), but I got error and the message is below:
(nemo_py3.6) root@38424d843eb8:/workspace/nemo/nemo/test# $NEMO_CODE_ROOT/nemo/test/script/setup_local.sh
cmd:  cd /workspace/nemo/nemo/test/jni/.. && ndk-build NDK_TOOLCHAIN_VERSION=clang APP_STL=c++_shared NDK_DEBUG=0
jni/libvpx.mk:24: jni/libvpx_android_configs/arm64-v8a/config.mk: No such file or directory
jni/libvpx.mk:25: jni/libvpx_android_configs/arm64-v8a/libs-.mk: No such file or directory
cat: jni/libvpx_android_configs/arm64-v8a/libvpx_srcs.txt: No such file or directory
make: *** No rule to make target 'jni/libvpx_android_configs/arm64-v8a/libs-.mk'.  Stop.

I look into directory jni(/workspace/nemo/nemo/test/jni) and there is no directory libvpx_android_configs. Can tell me how to fix this？ Thanks a lot : )

**Comment by chaos5958** [comment]
Oh, I just found that I comment the line that setup the configuration.
I fixed this in the commit (98ca09e78d3eb0483d2a64113a12dfec48fa1423).
Could you try with the latest version?

**Comment by estimate123** [comment]
Thankyou so much, I think this worked : ).  I generate libvpx_android_configs through the generate_libvpx_android_configs.sh in Exoplayer source code.

**Comment by yuqian2019** [comment]
> Thankyou so much, I think this worked : ). I generate libvpx_android_configs through the generate_libvpx_android_configs.sh in Exoplayer source code.

Can u detailed say steps to generate libvpx_android_configs folder? I observe the same problem.
